
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "service7ImplService", targetNamespace = "http://service/", wsdlLocation = "http://localhost:8989/service7?wsdl")
public class Service7ImplService
    extends Service
{

    private final static URL SERVICE7IMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICE7IMPLSERVICE_EXCEPTION;
    private final static QName SERVICE7IMPLSERVICE_QNAME = new QName("http://service/", "service7ImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8989/service7?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICE7IMPLSERVICE_WSDL_LOCATION = url;
        SERVICE7IMPLSERVICE_EXCEPTION = e;
    }

    public Service7ImplService() {
        super(__getWsdlLocation(), SERVICE7IMPLSERVICE_QNAME);
    }

    public Service7ImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICE7IMPLSERVICE_QNAME, features);
    }

    public Service7ImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE7IMPLSERVICE_QNAME);
    }

    public Service7ImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE7IMPLSERVICE_QNAME, features);
    }

    public Service7ImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Service7ImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Service7Impl
     */
    @WebEndpoint(name = "service7ImplPort")
    public Service7Impl getService7ImplPort() {
        return super.getPort(new QName("http://service/", "service7ImplPort"), Service7Impl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Service7Impl
     */
    @WebEndpoint(name = "service7ImplPort")
    public Service7Impl getService7ImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "service7ImplPort"), Service7Impl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICE7IMPLSERVICE_EXCEPTION!= null) {
            throw SERVICE7IMPLSERVICE_EXCEPTION;
        }
        return SERVICE7IMPLSERVICE_WSDL_LOCATION;
    }

}
